
spring.application.name=AventuraPe Platform
# Configuracion de la base de datos PostgreSQL para produccion usando la cadena de conexion proporcionada por Azure
spring.datasource.url=${AVENTURAPE_CONNECTIONSTRING}
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


# Spring Data JPA Configuration
spring.jpa.database: postgresql

# Configuracion de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Configuration Properties
authorization.jwt.secret = WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days = 7

# Application Information for Documentation

# Elements take their values from maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.ddl-auto: update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy= com.upc.aventurape.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

google.recaptcha.secret=6LfQ4CUrAAAAAJIK5lszu2zBqwoYElTKMetnbIjr
google.recaptcha.verify.url=https://www.google.com/recaptcha/api/siteverify
